---
common: &common
  agents:
    - "agent_count=8"
    - "boot_disk_size_gb=400"
    - "capable_of_building=platform"
    - "machine_type=quad"
    - "queue=${CI_LINUX_BUILDER_QUEUE:-v4-20-06-23-173521-bk12705-2627bc3f-d}"
    - "platform=linux"
    - "permission_set=builder"
    - "scaler_version=2"
    - "environment=${CI_ENVIRONMENT:-cn-production}"
  retry:
    automatic:
      - <<: *exit_bk_lost_connection
      - <<: *exit_bk_error
      - <<: *exit_docker_error

steps:
  - label: "frontend test"
    <<: *common
    command: cd superset-frontend && npm run test
